### ISSUE TITLE
release code

### ISSUE THREAD

**Issue by nlpLover123** [chuanyang-Zheng/Deep-Learning-Approach-Predicting-Knee-Osteoarthritis-Progression-from-MRI#1]
Hi, thanks for sharing your great work. I am also interested in Predicting Knee Osteoarthritis Progression. Will the code of your project be released ?

**Comment by chuanyang-Zheng** [comment]
Our code is modified from the GitHub repository https://github.com/kenshohara/3D-ResNets-PyTorch 

Our paper is still under review. Therefore, I will discuss with my collaborators about code release at the current state.

We have two ISMRM papers that are accepted, which may be helpful for your work.
[ISMRM Oral Presentation Paper 1](https://chuanyang-zheng.github.io/ISMRM%202022-3102.html)
[ISMRM Oral Presentation Paper 2](https://chuanyang-zheng.github.io/ISMRM%202022-4621.html)

If you have any questions, please let me know!
